FROM golang:1.17

WORKDIR /go/src/app
COPY . .

RUN go get -d -v . && \
    go build -v .

ENV PORT=8080
ENV MARIADB_USER_NAME=root
ENV MARIADB_USER_PASSWORD=12345
ENV MARIADB_HOST=mariadb

CMD sleep 5 && ./schablone-server $PORT $MARIADB_USER_NAME $MARIADB_USER_PASSWORD $MARIADB_HOST
