---
openapi: 3.0.3
info:
  title: Schablone Server
  description: E-Mail Template Management System
  version: 0.0.2
security:
  - ApiKeyAuth: []
paths:
  /user/list:
    get:
      security:
        - ApiKeyAuth: []
      description: List all users
      responses:
        '200':
          description: Successfully fetched all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
        '405':
          description: No permissions
  /user/create:
    post:
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
            minimum: 1
          description: The user name
        - in: query
          name: firstname
          required: true
          schema:
            type: string
            minimum: 1
          description: The first name of the user
        - in: query
          name: lastname
          required: true
          schema:
            type: string
            minimum: 1
          description: The last name of the user
        - in: query
          name: password
          required: true
          schema:
            type: string
            minimum: 1
          description: The password
      security:
        - ApiKeyAuth: []
      description: Create a new user
      responses:
        '200':
          description: Successfully created user
          content:
            application/json:
              schema:
                type: integer
                description: User ID
        '400':
          description: Invalid request
        '405':
          description: No permission
  /user/get/{userId}:
    get:
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
      security:
        - ApiKeyAuth: []
      description: Get user information
      responses:
        '200':
          description: Successfully fetched user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
  /user/login:
    get:
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
            minimum: 1
          description: The user name
        - in: query
          name: password
          required: true
          schema:
            type: string
            minimum: 1
          description: The user password
      security:
        - ApiKeyAuth: []
      description: Get API key
      responses:
        '200':
          description: Successfully fetched API key
          content:
            application/json:
              schema:
                type: string
                description: API Key
        '400':
          description: Invalid request
        '404':
          description: Access denied
  /user/modify/{userId}:
    post:
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
        - in: query
          name: username
          required: true
          schema:
            type: string
            minimum: 1
          description: The user name
        - in: query
          name: firstname
          required: true
          schema:
            type: string
            minimum: 1
          description: The first name of the user
        - in: query
          name: lastname
          required: true
          schema:
            type: string
            minimum: 1
          description: The last name of the user
        - in: query
          name: password
          required: true
          schema:
            type: string
            minimum: 1
          description: The password
      security:
        - ApiKeyAuth: []
      description: Modify user data
      responses:
        '200':
          description: Successfully modified user
        '400':
          description: Invalid parameters
        '405':
          description: No permission
  /group/list:
    get:
      parameters:
        - in: query
          name: groupId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The group ID
      security:
        - ApiKeyAuth: []
      description: List all groups
      responses:
        '200':
          description: Successfully fetched list of groups user has permissions to
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
        '400':
          description: Invalid request
  /group/get/{groupId}:
    get:
      parameters:
        - in: path
          name: groupId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The group ID
      security:
        - ApiKeyAuth: []
      description: Get group info
      responses:
        '200':
          description: Successfully fetched all posts from JSONPlaceholder
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '400':
          description: Invalid request
  /group/create:
    post:
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
            minimum: 1
          description: Group title
        - in: query
          name: parentGroupId
          required: true
          schema:
            type: string
            minimum: 1
          description: Parent Group ID
      security:
        - ApiKeyAuth: []
      description: Create group
      responses:
        '200':
          description: Successfully created group
          content:
            application/json:
              schema:
                type: integer
                description: Group ID
        '405':
          description: Group name does already exist
        '400':
          description: Invalid request
  /template/create:
    post:
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
            minimum: 1
          description: Template title
        - in: query
          name: subject
          required: true
          schema:
            type: string
            minimum: 1
          description: Template subject
        - in: query
          name: content
          required: true
          schema:
            type: string
            minimum: 1
          description: Template content
        - in: query
          name: initialGroup
          required: true
          schema:
            type: integer
            minimum: 1
          description: Group ID of the templates parent group
      security:
        - ApiKeyAuth: []
      description: Create template
      responses:
        '200':
          description: Successfully created a template
          content:
            application/json:
              schema:
                type: integer
                description: Template ID
        '400':
          description: Invalid request
        '405':
          description: No permission
  /template/edit/checkin:
    post:
      parameters:
        - in: query
          name: templateId
          required: true
          schema:
            type: integer
            minimum: 1
          description: Template ID
        - in: query
          name: name
          required: true
          schema:
            type: string
            minimum: 1
          description: Template title
        - in: query
          name: subject
          required: true
          schema:
            type: string
            minimum: 1
          description: Template subject
        - in: query
          name: content
          required: true
          schema:
            type: string
            minimum: 1
          description: Template content
      security:
        - ApiKeyAuth: []
      description: Modify template after check-out
      responses:
        '200':
          description: Successfully checked in template
        '400':
          description: Invalid arguments
        '405':
          description: File not checked out 
  /template/edit/checkout:
    post:
      parameters:
        - in: query
          name: templateId
          required: true
          schema:
            type: integer
            minimum: 1
          description: Template ID
      security:
        - ApiKeyAuth: []
      description: Mark template as being edited
      responses:
        '200':
          description: Successfully checked out template
        '400':
          description: Invalid arguments
        '405':
          description: File already checked out or no permission
  /template/list:
    get:
      parameters:
        - in: query
          name: groupId
          required: true
          schema:
            type: integer
          description: Group ID
      security:
        - ApiKeyAuth: []
      description: List templates of a specific group
      responses:
        '200':
          description: Successfully fetched all templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Template'
  /template/get/{templateId}:
    get:
      parameters:
        - in: path
          name: templateId
          required: true
          schema:
            type: integer
          description: Template ID
      security:
        - ApiKeyAuth: []
      description: Get a template
      responses:
        '200':
          description: Successfully fetched template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
  /macro/create:
    post:
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
            minimum: 1
          description: Macro title
        - in: query
          name: content
          required: true
          schema:
            type: string
            minimum: 1
          description: Macro content
        - in: query
          name: initialGroup
          required: true
          schema:
            type: integer
            minimum: 1
          description: Group ID of the templates parent group
      security:
        - ApiKeyAuth: []
      description: Create macro
      responses:
        '200':
          description: Successfully created a macro
          content:
            application/json:
              schema:
                type: integer
                description: Macro ID
        '400':
          description: Invalid request
        '405':
          description: No permission
  /macro/edit/checkin:
    post:
      parameters:
        - in: query
          name: macroId
          required: true
          schema:
            type: integer
            minimum: 1
          description: Macro ID
        - in: query
          name: name
          required: true
          schema:
            type: string
            minimum: 1
          description: Macro title
        - in: query
          name: content
          required: true
          schema:
            type: string
            minimum: 1
          description: Macro content
      security:
        - ApiKeyAuth: []
      description: Modify macro after check-out
      responses:
        '200':
          description: Successfully checked in macro
        '400':
          description: Invalid arguments
        '405':
          description: Macro not checked out 
  /macro/edit/checkout:
    post:
      parameters:
        - in: query
          name: macroId
          required: true
          schema:
            type: integer
            minimum: 1
          description: Macro ID
      security:
        - ApiKeyAuth: []
      description: Mark macro as being edited
      responses:
        '200':
          description: Successfully checked out macro
        '400':
          description: Invalid arguments
        '405':
          description: Macro already checked out or no permission
  /macro/list:
    get:
      parameters:
        - in: query
          name: groupId
          required: true
          schema:
            type: integer
          description: Group ID
      security:
        - ApiKeyAuth: []
      description: List macros of a specific group
      responses:
        '200':
          description: Successfully fetched all macros
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Macro'
  /macro/get/{macroId}:
    get:
      parameters:
        - in: path
          name: macroId
          required: true
          schema:
            type: integer
          description: Macro ID
      security:
        - ApiKeyAuth: []
      description: Get a macro
      responses:
        '200':
          description: Successfully fetched macro
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Macro'
  /group/add_macro:
    post:
      parameters:
        - in: query
          name: macroId
          required: true
          schema:
            type: integer
          description: Macro ID
        - in: query
          name: groupId
          required: true
          schema:
            type: integer
          description: Group ID
      security:
        - ApiKeyAuth: []
      description: Add macro to group
      responses:
        '200':
          description: Successfully changed group
        '400':
          description: Invalid arguments
        '405':
          description: No permission or action has already taken place
  /group/remove_macro:
    post:
      parameters:
        - in: query
          name: macroId
          required: true
          schema:
            type: integer
          description: Macro ID
        - in: query
          name: groupId
          required: true
          schema:
            type: integer
          description: Group ID
      security:
        - ApiKeyAuth: []
      description: Remove macro from group
      responses:
        '200':
          description: Successfully changed group
        '400':
          description: Invalid arguments
        '405':
          description: No permission or action has already taken place
  /group/add_template:
    post:
      parameters:
        - in: query
          name: templateId
          required: true
          schema:
            type: integer
          description: Template ID
        - in: query
          name: groupId
          required: true
          schema:
            type: integer
          description: Group ID
      security:
        - ApiKeyAuth: []
      description: Add template to group
      responses:
        '200':
          description: Successfully changed group
        '400':
          description: Invalid arguments
        '405':
          description: No permission or action has already taken place
  /group/remove_template:
    post:
      parameters:
        - in: query
          name: templateId
          required: true
          schema:
            type: integer
          description: Template ID
        - in: query
          name: groupId
          required: true
          schema:
            type: integer
          description: Group ID
      security:
        - ApiKeyAuth: []
      description: Remove template from group
      responses:
        '200':
          description: Successfully changed group
        '400':
          description: Invalid arguments
        '405':
          description: No permission or action has already taken place
  /group/add_user:
    post:
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: integer
          description: User ID
        - in: query
          name: groupId
          required: true
          schema:
            type: integer
          description: Group ID
      security:
        - ApiKeyAuth: []
      description: Add user to group
      responses:
        '200':
          description: Successfully changed group
        '400':
          description: Invalid arguments
        '405':
          description: No permission or action has already taken place
  /group/remove_user:
    post:
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: integer
          description: User ID
        - in: query
          name: groupId
          required: true
          schema:
            type: integer
          description: Group ID
      security:
        - ApiKeyAuth: []
      description: Remove user from group
      responses:
        '200':
          description: Successfully changed group
        '400':
          description: Invalid arguments
        '405':
          description: No permission or action has already taken place
  /group/change_parent_group:
    post:
      parameters:
        - in: query
          name: parentGroupId
          required: true
          schema:
            type: integer
          description: Parent Group ID
        - in: query
          name: groupId
          required: true
          schema:
            type: integer
          description: Group ID
      security:
        - ApiKeyAuth: []
      description: Add group parent to group
      responses:
        '200':
          description: Successfully changed group
        '400':
          description: Invalid arguments
        '405':
          description: No permission or action has already taken place

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        groupIds:
          type: array
          items:
            type: integer
    Template:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        attachementIds:
          type: array
          items:
            type: integer
    Macro:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
    Group:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        parentId:
          type: integer
