-- MySQL Script generated by MySQL Workbench
-- Mon 17 Jan 2022 12:35:18 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(50) NULL,
  `Lastname` VARCHAR(50) NULL,
  `Username` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Hash` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Template` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Subject` VARCHAR(45) NULL,
  `Content` BLOB NULL,
  `IsBeingEditedBy` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `isBeingEdited_idx` (`IsBeingEditedBy` ASC) VISIBLE,
  CONSTRAINT `isBeingEdited`
    FOREIGN KEY (`IsBeingEditedBy`)
    REFERENCES `mydb`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Macro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Macro` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Content` BLOB NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TemplateGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TemplateGroup` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NULL,
  `ParentTemplateGroup` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `parentTemplateGroup_idx` (`ParentTemplateGroup` ASC) VISIBLE,
  CONSTRAINT `parentTemplateGroup`
    FOREIGN KEY (`ParentTemplateGroup`)
    REFERENCES `mydb`.`TemplateGroup` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attachement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attachement` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BelongsToTemplate` INT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `BelongsToTemplate_idx` (`BelongsToTemplate` ASC) VISIBLE,
  CONSTRAINT `BelongsToTemplate`
    FOREIGN KEY (`BelongsToTemplate`)
    REFERENCES `mydb`.`Template` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SavedAttachement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SavedAttachement` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Path` VARCHAR(100) NULL,
  `BelongsToAttachement` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `BelongsToAttachement_idx` (`BelongsToAttachement` ASC) VISIBLE,
  CONSTRAINT `BelongsToAttachement`
    FOREIGN KEY (`BelongsToAttachement`)
    REFERENCES `mydb`.`Attachement` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_TemplateGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_TemplateGroup` (
  `BelongsToUser` INT NOT NULL,
  `TemplateGroup` INT NOT NULL,
  `UserHasWriteAccess` TINYINT NULL,
  `UserHasUserModifyAccess` TINYINT NULL,
  PRIMARY KEY (`BelongsToUser`, `TemplateGroup`),
  INDEX `User_idx` (`BelongsToUser` ASC) VISIBLE,
  INDEX `TemplateGroup_idx` (`TemplateGroup` ASC) VISIBLE,
  CONSTRAINT `User`
    FOREIGN KEY (`BelongsToUser`)
    REFERENCES `mydb`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TemplateGroup`
    FOREIGN KEY (`TemplateGroup`)
    REFERENCES `mydb`.`TemplateGroup` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Template_TemplateGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Template_TemplateGroup` (
  `BelongsToTemplate` INT NOT NULL,
  `TemplateGroup` INT NOT NULL,
  PRIMARY KEY (`BelongsToTemplate`, `TemplateGroup`),
  INDEX `Template_idx` (`BelongsToTemplate` ASC) VISIBLE,
  INDEX `TemplateGroup_idx` (`TemplateGroup` ASC) VISIBLE,
  CONSTRAINT `Template`
    FOREIGN KEY (`BelongsToTemplate`)
    REFERENCES `mydb`.`Template` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TemplateGroup`
    FOREIGN KEY (`TemplateGroup`)
    REFERENCES `mydb`.`TemplateGroup` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Macro_TemplateGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Macro_TemplateGroup` (
  `BelongsToMacro` INT NOT NULL,
  `TemplateGroup` INT NOT NULL,
  PRIMARY KEY (`BelongsToMacro`, `TemplateGroup`),
  INDEX `Macro_idx` (`BelongsToMacro` ASC) VISIBLE,
  INDEX `TemplateGroup_idx` (`TemplateGroup` ASC) VISIBLE,
  CONSTRAINT `Macro`
    FOREIGN KEY (`BelongsToMacro`)
    REFERENCES `mydb`.`Macro` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TemplateGroup`
    FOREIGN KEY (`TemplateGroup`)
    REFERENCES `mydb`.`TemplateGroup` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
