// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yW0U/bPhDH/xXrfr/H0JbxljfEEOoYG1KYNAn1wTiXxMixjX1Biqr+75Odpg10rN1a",
	"TQPx1CQ+f3338fWrm4MwtTUaNXlI5+BFhTWPjzdYW8UJw7N1xqIjiXGFE/EQh5qmefwiCev4QK1FSEFq",
	"whIdLJL+C3eOt+FdGE2oaRDsyUldhjWZv6AhSeFPdqzlzd09CopfPIrGSWqzmGLM6tTKS2xPG6pishpS",
	"qJDn6CABzesg8P3o9Hp6dIktrFOOu2ARRKUuTNiboxdOWpImiJwfXXGpWE+KXXHNy8iFZa0nrGGVO2Si",
	"4nfKaGQZusd49CM63wlNRpPRcajUWNTcSkjhZDQZnUACllMVixCcsDSuHQuHy2spkTaT+iw9Ma4Us8aT",
	"h6jpeFic5pDCBdLZUumsEwpnOF4jofOQ3j7X66NZV0nS8Xto0LVrfPEnAYcPjXSYQ0quwWTZTiHHWmpZ",
	"NzWkx8nGLc7CRm+N9t11fZhMNsvKGiHQ+6JRqmUFkqgwX5fJCmdq9in7+uVacYGVUeF2h+0QKxs2wu1s",
	"MQsBK64l0njev03zxQEIDx6n+TbQNxWy/ng2/diTDg2wBi2Gcr+Fe/V/+ld4K+npAIxD5B+ifdbEr58t",
	"LZ1of4/oPe3dI55wxVzSAaieB5l3ph3T7T7Qh3pmCuYtCllIwUpnGvsryrs4w0UQedkS4hlb/GBXDxhM",
	"PtxaJUVMenzvQyLzgeBqmvrfYQEp/DdeD2nj5YQ2Xo1nGzNWgPuX7rDx6Pb3mm8e3W4+E3w8nPnyhYXV",
	"1+vfkWecQ7o6FntSXf7sNns8A/t07ngDXPecNwLIXWeNN9+j/nA9mr336GyxPeJHAAAA//8sR7FFqg8A",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

