// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZX2/bNhD/KgS3RyXO2u7Fb0HXGV7XLoATYECRB0Y6WWwkUiVP6YzA333gUf8aSzad",
	"uIkf8lKr4vF4x9/d706Xex7rotQKFFo+vec2zqAQ9DgzuirdQ2l0CQYl0GuZuH9xVQKfcqkQlmD4OuJK",
	"FNBbsWikWrqFUhhQOB/cto6aV/rmK8To5C+hKHOBsHm0QBTOPlLnjUEo7LA99RthjFi5/8daISgcNHHM",
	"J5SYDzk1ZPaVBbNpciqNxdGrWbor3t+VMXNzseWsyoIZWdx0Zx1xC3FlJK4WdONk2XkpP8LqvMKMDFZ8",
	"yjMQCRjewM//PTm/mJ98hBXvzKZdfO2USpVqtzcBGxtZotROyYeTT0LmrAGefRJKLAlmtlhZhIK3UPBF",
	"nImbXCtgCzB3dPQdGOsVnZ2enb5xzuoSlCgln/K3p2enb7mLQszIiQld+iQ20MSYtrhp03taZyTMSaER",
	"bsnFMb/QFik9vBSpN6IABGP59MtDXSTKvAeRv7dvFZhVd230E3ED3yppIOFTNBVEdTY64wqpZFEVfPpb",
	"tIHetdtoS62sh+nN2dmmP4sqjsHatMrzFfPOJ7V364i/G9oyV3cilwlzVoFFL/f7ppx3z7nAEg2WidyA",
	"SFYM/pP2x1iiu+lH0Zfr9bUTqEFZAk7u66RYu4OWMADNDNBbziicHoIzA49N8ztPduFzmdVAs/kfDUAu",
	"Xjp8lq2ivSDqeG4Eox4pibLMZUxuTL5aZ9d9T/mvBlI+5b9MOrqe1Fw98URN+bUF8xQwziBhIs+ZC3nL",
	"UqML9tfin88XuYgh03niaSQsGPaANZc+wwbR/FtaJKNI1o7C6eQeA+SDTHtxJFueD4D0IfUHQuzum+m0",
	"vlHmmJ9lwrISTCGt40rLUB8YaqzZO5RZG/lBcm1KQRi/toXjp1FsNHqkrXzJHD60Wz30uU28DZ/brT53",
	"SREdsE+tK591L2L3jUJIJE7iDOJbqcZj8ZNOZLpqTWYiRTCMtp3oCrfG5odE4vv6gNAAHaWlxoKnMFP0",
	"mhdHmBcuQiBhUoUnhjDLqqAvsrHU+FPmwJTGVr0L1kdniNs8niLC3PYSxLIbkGrJ3G5IwhLEZ9IRZMjj",
	"4dMVHhy/pk/un6ENU0+hPeqgu6va3kSL8SI8gxbG3uPuVnq2tY0OxPBZu+d23BDaXXVhsB80u7vgRtS6",
	"5s2WEMtUxiOfoD1UQjrj2dO74pfphC97SfeoZth9WrQXG4iZ65hD+1jBFHynHnuQDK8smMAuNgPfqtcV",
	"eQindohzuMKZAaMhlf+A1ynD2o4RE7qJ1kFtyEW4Ce2c66AWlMLa79okI4f2lp+7p6areIlumvKASop7",
	"2lVOKHilSrUpKAeGOMulQ/0TNpchpWP1pGrUHOFUhubBoSS1H8Lh2IVNXpyoHUOrri4/n+mv7NC0ew+W",
	"924cNE/2Khi5XvpvzdEMOb+Ys1uajQ9fNSk42jJBp74QS+4Itc0/aATETIPGXhHzblPunHSzBJSEZJ+A",
	"KWj68AO5bh1TEACJQDHaaXjBI2HX6LXDee1wtnc4lAEytAD2wvlgXc5Oif8DAAD//7Awo3UiHwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

