// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb32/bNhD+Vwhuj06ctd2L34KuC7IuXbC0wICiKFjpbLGRSJWk0hmB//eBR/2wY1Gi",
	"VDtOO7/UqXXiUfy+u/uOou9pJLNcChBG09k91VECGcM/L5QscvtHrmQOynDAr3ls/zXLHOiMcmFgAYqu",
	"JlSwDNauaKO4WNgLOVMgzGXrbatJ9ZX89BkiY+2vWKTktt9ICgPCtLrwzclwk7ZNqs3tW8jylBnY9syM",
	"YXZZ8CncGhjItMel+4YpxZb2//ue9jsNanvKc6608SKysMgOfxTfdFPW4avQoDwXtx9nNaEaokJxs7zB",
	"FceZnef8NSzPC5PghAWd0QRYDIpWrKP/nJxfX568hiVtpo130ZUdlIs5MioGHSmeGy7tIK9OrhhPSQU8",
	"uWKCLRBmcrPUBjJaQ0FvooR9SqUAcgPqDl3fgdJuoLPTs9Nn9mFlDoLlnM7o89Oz0+fUkt8k+BBTXPQp",
	"i+OPWU1wqc32tM7jmKAJMZLgXRRHVswa2Dii11IbDM/zOHbhgmHGMjCgNJ29fzgmGpHL3+jErd+XAtSy",
	"WT50dxnTCVXwpeAKYjozqoBJmQ/aQ/ehE5yR30nJumFOPlhrnUuhHReenZ1tr9hNEUWg9bxI0yWJEiYW",
	"EJcrt5rQF223XIo7lvKYMLUoMkx+aPnrtuUbSXJQGdcWbCIVYZG9QhKmCUsVsHhJDLsFQfKURbBBYkRi",
	"nb7vP6w+WIM1Npj1vOMlRGUVxok6l/XQoqa+F7TK75EcByFHUWV3LzGsRRgpsFL0EMLa+EGyvo5EeHQi",
	"uLl+dDrq46KWZV5OoAlx9gHceInjX6P5RWnayRJnSnqQzJsBj6R5fNIo6CwqL/F6LzXcKD18cOg4qdQO",
	"EH50oZNxwbMio7NfJtsycd/863LuYcmarGd5nvIIF2/6WdsJ3q+N7eXxFh9Xk07uIRKh3LPPCtp4mefm",
	"YReKxBIatsG/XJtBPFuAmd6X8beyjhbQwrYLMGVWQin+kG8X4HCqPhGvbuWSlNxdw99q7WE5oQX43vwQ",
	"jPzPCuZ0Rn+aNh32tGyvpy7N9mE+BxMlEBOWpsRGsSZzJTPyx81fb65tQkhkGrsWLIwMA2BNuUsarWj+",
	"ybXBSaGt9sJp7cYAOSK77xXJukcOgPRh2xwIsV1vIuflijpVZ8tAUx80MXIvUCvI5B30daV/o1XZmCIN",
	"e0qHu+HYnX6/EqIkRn+DWnKj7lHD6XFsVH8cnnT3qiVHMLGF8+PYs353nMBsHdp+ZGV52CYB1oSw9sOV",
	"j8drP5y/Sj20e2yu7shpRUErEkzSJFtd9flVPLXNhgtuOEur5v5AMspb9Ee2Qqykz7c2QxtxMIjlEHMz",
	"jRKIbrnwc/1Kxny+LKUTmxtQBO85kYXxc/9VzM3Lcuj966dO4Cf/h4gbk48huoWYcBFIxP6U7B5USFMP",
	"bjkyjpL2Tj8nmbqtGKnJJ+BiQeytEAcw0vH2oJQcj5YszI7hqmrlugepiBidVnBPpVyi7j0V5qmgF+Ag",
	"qz77N1QeAra5mTKqBdvnBorrK0O76xLvARD073+gnbblmBGdQ8TnPPKI2gqFkP2QR5Sau93/uKpiatT+",
	"B0vTckUDYar0T6jSNE2nuZ3eqvYyTG/WzejjFcDapS7cUYl2p83VXfs9qt1vU7ubGxijBW/N4kNo3jrk",
	"BsneelcoRPlWyzRA/O5sa2iYBD4mgSclwIMDo1/U/c5TGCnBWyKkX4U3ARIgxLcCJECLP06EfJsi3zV+",
	"O9TkNagoy5ul6lPmXsVxATWMa38GvPPcxnFTpY/dA9+nUK93+EOVYMOEYej0K/ZGRASK9mruP7Ruf7sW",
	"eaOle720gagVGlSocmdEwFd8cdCaEd9pUIG6PSnfP5Rl2fe6YMdVOwGCx7HdcYtS0JaP0zaF5uz2TueQ",
	"svAp1Ce6dzqDnGn9VarYe16nvvwUjuo0r5VGqnVc30PodAwuLFbu5Vd3ocKI4GIuVYYL05YI7VqUH2FH",
	"c4rNd3KbZSrgldzBDubgC8fQzDcM4XDswg7fWFPtQ6ssWfsvH+90249FBpQO9xg7jZNBVSiVC9fFeiPk",
	"/PqS3OJPS9qXGgd4srUHvX5fqdcu+MZveWo/YbSqABtEqhct88CxSQyCQzyEUxlufWzk3849EsQoZoZ5",
	"FY4zfCIJeHJUVkdl1d3bYwTw0Bq5RuedCaFei/8CAAD//0AW62r7OgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

