// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Group defines model for Group.
type Group struct {
	Id       *int    `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	ParentId *int    `json:"parentId,omitempty"`
}

// Template defines model for Template.
type Template struct {
	AttachementIds *[]int  `json:"attachementIds,omitempty"`
	Content        *string `json:"content,omitempty"`
	Id             *int    `json:"id,omitempty"`
	Title          *string `json:"title,omitempty"`
}

// User defines model for User.
type User struct {
	Firstname *string `json:"firstname,omitempty"`
	GroupIds  *[]int  `json:"groupIds,omitempty"`
	Id        *int    `json:"id,omitempty"`
	Lastname  *string `json:"lastname,omitempty"`
	Username  *string `json:"username,omitempty"`
}

// PostGroupCreateParams defines parameters for PostGroupCreate.
type PostGroupCreateParams struct {
	// Group title
	Name string `json:"name"`
}

// GetGroupListParams defines parameters for GetGroupList.
type GetGroupListParams struct {
	// The group ID
	GroupId int `json:"groupId"`
}

// PostTemplateCreateParams defines parameters for PostTemplateCreate.
type PostTemplateCreateParams struct {
	// Template title
	Name string `json:"name"`

	// Template subject
	Subject string `json:"subject"`

	// Template content
	Content string `json:"content"`
}

// PostTemplateEditCheckinParams defines parameters for PostTemplateEditCheckin.
type PostTemplateEditCheckinParams struct {
	// Template ID
	TemplateId int `json:"templateId"`

	// Template title
	Name string `json:"name"`

	// Template subject
	Subject string `json:"subject"`

	// Template content
	Content string `json:"content"`
}

// PostTemplateEditCheckoutParams defines parameters for PostTemplateEditCheckout.
type PostTemplateEditCheckoutParams struct {
	// Template ID
	TemplateId int `json:"templateId"`
}

// GetTemplateListParams defines parameters for GetTemplateList.
type GetTemplateListParams struct {
	// Group ID
	GroupId int `json:"groupId"`
}

// PostUserCreateParams defines parameters for PostUserCreate.
type PostUserCreateParams struct {
	// The user name
	Username string `json:"username"`

	// The first name of the user
	Firstname string `json:"firstname"`

	// The last name of the user
	Lastname string `json:"lastname"`

	// The password
	Password string `json:"password"`
}

// GetUserLoginParams defines parameters for GetUserLogin.
type GetUserLoginParams struct {
	// The user name
	Username string `json:"username"`

	// The user password
	Password string `json:"password"`
}

// PostUserModifyUserIdParams defines parameters for PostUserModifyUserId.
type PostUserModifyUserIdParams struct {
	// The user name
	Username string `json:"username"`

	// The first name of the user
	Firstname string `json:"firstname"`

	// The last name of the user
	Lastname string `json:"lastname"`

	// The password
	Password string `json:"password"`
}

